CREATE TABLE IF NOT EXISTS todo_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NULL,
    user_id BIGINT NOT NULL,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_todo_item_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
